Feat/he/dicetest etc
572018/Prosjekt2Yatzy pull request #5
Opened 2022-03-17 17:16 UTC by 591334

2022-03-17 17:20 UTC, 572018 requested changes
DiceTest kan være en test som tester at terningen ruller mellom 1 og 6 i en test

2022-03-17 18:39 UTC, h584969 reviewed
See veldig bra ut slik det er nå👍👍👍

2022-03-17 18:39 UTC, h584969 commented on src/test/java/diceTest/diceTest.java
> +		assertTrue(roll >= 1);
Kanskje gjøre en noen iterasjoner og sjekke at alle er over 1?

2022-03-18 10:46 UTC, 572018 approved these changes

2022-03-18 14:19 UTC, merged